data_dir: "/home/pervinco/Datasets/WFLW/dataset"
save_dir: "./runs"
version: "v2"

epochs: 500
image_size: 112
batch_size: 256

init_lr: 0.0001
weight_decay: 0.000001
lr_patience: 40
min_lr: 0.00001

build_test: False
