data_dir: "/home/pervinco/Datasets/WFLW/dataset"
save_dir: "./runs"
model_version: "v2"

epochs: 1000
image_size: 112
batch_size: 256

init_lr: 0.001 ## 0.0001
weight_decay: 0.000001 ## 1e-6
lr_patience: 40
min_lr: 0.00001
T_0: 100
T_mult: 2

build_test: False
